[startup.wiki]
name = "bash"
protected = true #set protected to true to respawn the container if it crashed

[startup.wiki.args]
script = """
sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
export HOME=/root
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

. /sandbox/env.sh
cd /sandbox
git clone $REPO_URL -b $REPO_BRANCH
ln -s $src1 $dest1
ln -s $src2 $dest2
ln -s $src3 $dest3

exec js_shell \"j.tools.markdowndocs.webserver()\"
"""